### PR TITLE
Initial commit

### PR DESCRIPTION
**Pull request by Sajj96**
## Description

Added Prettier and Eslint configurations. For devs must install Prettier and Eslint extensions in their Editor 

## Screenshot

Include screenshot(if applicable)
Chrome extension for capturing GIF Screenshot 

https://chrome.google.com/webstore/detail/capture-to-a-gif/eapecadlmfblmnfnojebefkbginhggeh
## Type of change

Please select the relevant option

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes.

- [ ] End to end
- [ ] Integration

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have linted my code prior to submission
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

## PIVOTAL TRACKER LINK
Please provide (a) link(s) to the work item in JIRA

### CODE REVIEW

**Comment by DrKimpatrick** [comment]
@Sajj96 Please resolve the conflicts

**Comment by Sajj96** [comment]
Let figure it out why it is conflicting

**Review by younggeeks — COMMENTED** [review]
Branch name should follow this format chore-add-eslint

**Comment by Sajj96** [comment]
Closed

**Pull request closed without merging**
